### ISSUE TITLE
getAttribute documented, not implemented

### ISSUE THREAD

**Issue by perry-mitchell** [bbozzay/parse5-query-htmltree#3]
In your docs you reference [`getAttribute`](https://github.com/bbozzay/parse5-query-htmltree#getattributename), but only `hasAttribute` is implemented:

https://github.com/bbozzay/parse5-query-htmltree/blob/master/src/index.js#L11-L29

**Comment by bbozzay** [comment]
The walk function imported into src/index.js modifies the returned node so that it has these additional properties and methods: classList, hasAttributes, and getAttribute. TreeQuery in index.js provides the methods for filtering the array of nodes. 

If you have mocha installed locally, you can run: mocha test/query.js and check for yourself. I do need to clean up this project a bit when I have time and also add some better development docs. Feel free to contribute if you feel inclined!
